name: Django Testing

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    step:
    - uses: actions/checkout@v2

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Deps
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with Flake8
      run:
        pip install flake8
        flake8

    - name: Coverage report
      run:
        pip install coverage
        coverage run manage.py test
        coverage report